name: weather03
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
#  adaptive_icon_background: "assets/icon/background.png"
#  adaptive_icon_foreground: "assets/icon/foreground.png"


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.3.0
  shared_preferences: ^2.5.2
  intl: ^0.20.2
  geolocator: ^13.0.2
  geocoding: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf